config/routes.rb
Hate::Application.routes.draw do
  get "comments/create"

  get "likes/agree"

  get "hatestatements/new"

  get "sessions/new"

  get "users/new"

  get "content/home"

  get "content/about"

  root :to => 'hatestatements#new'

  get "new_hate" => "hatestatements#new", :as => "new_hate"

  get "hates" => "hatestatements#showhate", :as => "hates"
  match "stats" => "hatestatements#hatestat"
  
  match "hate/:id" => "hatestatements#singlehate"
  match "hates/:hater" => "hatestatements#showhate"
  match "agree/:hate" => "likes#agree"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in"  => "sessions#new",     :as => "log_in"
  get "sign_up" => "users#new",        :as => "sign_up"

  resources :users
  resources :sessions
  resources :hatestatements
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/hatestatement.rb
class Hatestatement < ActiveRecord::Base
  attr_accessible :statement, :profanity

  validates_presence_of :statement
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_uniqueness_of :name

  def self.authenticate(name,password)
    user = find_by_name(name)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    if current_user
      @comment.submitter = current_user.name
    else
      @comment.submitter = "Anonymous"
    end
    @comment.save
    redirect_to :back
  end

end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def home
    @hatestatement = Hatestatement.new  
  end

  def about
  end

end

app/controllers/hatestatements_controller.rb
class HatestatementsController < ApplicationController
 
  def new
    @hates = Hatestatement.find(:all)
    @post = Hatestatement.new
  end

  def showhate
    @hates = Hatestatement.find(:all)
  end

  def create
    @post = Hatestatement.new(params[:hatestatement])
    if current_user
      @post.submitter = current_user.name
    else
      @post.submitter = "notloggedin"
    end
    @post.profanity = false
    
    ["shit","fuck","cunt","piss","nigger","rape"].each do |p|
      if @post.statement.downcase.include? p
        @post.profanity = true
        break
      end
    end

    @post.ip = request.remote_ip()

    if @post.save
      redirect_to root_url, :notice => "Submitted!"
    else
      redirect_to root_url, :notice => "Failed!"
    end
  end
  
  def singlehate
    @comment = Comment.new
    @comments = Comment.find_all_by_statementid(params[:id])
    @hates = Hatestatement.find(:all)
      @wordhash = Hash.new
      @bigrams = Hash.new
      @trigrams = Hash.new
      @hates.each do |h|
        state = h.statement.split(" ")
        state.each_with_index do |s,i|
          if i < state.size - 1
            c = s.downcase.gsub(/[^0-9a-z]/i,'')
            n = state[i+1].downcase.gsub(/[^0-9a-z]/i,'')
            @bigrams[[c,n]] = (@bigrams[[c,n]] ||= 0) + 1
          end
          if i < state.size - 2
            nn = state[i+2].downcase.gsub(/[^0-9a-z]/i,'')
            @trigrams[[c,n,nn]] = (@trigrams[[c,n,nn]] ||= 0) +1 
          end
        end
      end
      @hates.each do |h|
        if h
          h.statement.split(" ").each do |w|
            word = w.downcase.gsub("'s","").gsub(/[^0-9a-z]/i,'')
            @wordhash[word] = (@wordhash[word] ||= 0)+1
          end
        end
      end
      @stopwords = File.open("/ruby/kungfu/ruby-hax/common.txt").read.split
      @stopwords.each{|s| s.gsub!(/\d/,''); @wordhash[s] = 0; @wordhash.delete(s)}
      @hate = Hatestatement.find_by_id(params[:id])
      @topthemes = []
      @wordhash.sort{|b,a| a[1] <=> b[1]}[0..(@wordhash.size/4)-1].each{|e| @topthemes << e[0]}
      @themes = @hate.statement.split(" ").map(&:downcase).map{|s| s.gsub("'s",""); s.gsub("'","");} & @topthemes
  end

  def hatestat
      @hates = Hatestatement.find(:all)
      @wordhash = Hash.new
      @bigrams = Hash.new
      @trigrams = Hash.new
      @hates.each do |h|
        state = h.statement.split(" ")
        state.each_with_index do |s,i|
          if i < state.size - 1
            c = s.downcase.gsub(/[^0-9a-z]/i,'')
            n = state[i+1].downcase.gsub(/[^0-9a-z]/i,'')
            @bigrams[[c,n]] = (@bigrams[[c,n]] ||= 0) + 1
          end
          if i < state.size - 2
            nn = state[i+2].downcase.gsub(/[^0-9a-z]/i,'')
            @trigrams[[c,n,nn]] = (@trigrams[[c,n,nn]] ||= 0) +1 
          end
        end
      end
      @hates.each do |h|
        if h
          h.statement.split(" ").each do |w|
            word = w.downcase.gsub(/[^0-9a-z]/i,'')
            @wordhash[word] = (@wordhash[word] ||= 0)+1
          end
        end
      end
      @stopwords = File.open("/ruby/kungfu/ruby-hax/common.txt").read.split
      @stopwords.each{|s| s.gsub!(/\d/,''); @wordhash[s] = 0; @wordhash.delete(s)}
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def agree
    if current_user
      username = current_user.name
    else
      username = "notloggedin"
    end
    if Like.find_by_sql("SELECT * FROM LIKES WHERE STATEMENTID = #{params[:hate]} & LIKER = \"#{username}\"").size == 0
      Like.create(statementid: params[:hate], liker: username)
    end
    redirect_to :back
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:name],params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/hatestatements_helper.rb
module HatestatementsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/content/about.html.erb
<h1>Content#about</h1>
<p>Find me in app/views/content/about.html.erb</p>

app/views/content/home.html.erb
<div class="centerbox">
  <br>
  <div class="innerbox">
    <center><h1 class="bigtitle">What do you hate?</h1></center>
    <div class="textbar">

      <%= form_for :hatestatement, :remote => true, :url => {:controller => "hatestatements", :action => "create"} do |f| %>
        <%= f.text_field :statement%>
        <p class="button">
          <%=f.submit%>
        </p>
      <% end %>
    
    </div>
  </div>
  <br>
</div>

app/views/hatestatements/hatestat.html.erb
<span style="color:white;">
  Top 20 words in a hate:
  <br>
  <% @wordhash.sort{|b,a| a[1] <=> b[1]}[0..19].each do |w| %>
  <%= w %>
<% end %>
<hr>
  Top 20 bigrams in a hate:
  <br>
<% @bigrams.sort{|b,a| a[1] <=> b[1]}[0..19].each do |b| %>
  <%= b %>
<% end %>
<hr>
  Top 20 trigrams in a hate:
  <br>
<% @trigrams.sort{|b,a| a[1] <=> b[1]}[0..19].each do |t| %>
  <%= t %>
<% end %>
</span>

app/views/hatestatements/new.html.erb
<center><p class=lighthate style="font-weight:300;font-size:120%;padding-top:100px;letter-spacing:20px;font-variant:small-caps;">TheAntisocialNetwork</p></center>
<div class="centerbox" id="plane">
  <br>
  <div class="innerbox">
    <center><h1 class="bigtitle">What do you <a href="/hates" style="text-decoration:none;"><span class="lighthate">hate</span></a>?</h1></center>
    <center class="rotateme">Contribute to a database containing <a href="/hates"><span class="lighthate"><%=@hates.size%></span></a> other annoyances!</center>
    <div class="textbar">

      <%= form_for @post do |f| %>
        <div class="ihate">I hate: </div><%= f.text_field(:statement, :class => "hate_input")%>
        <div class="ihate">...</div>
      <% end %>
      <%= javascript_tag "document.getElementById('hatestatement_statement').focus();"%>
    </div>
  </div>
  <br>
</div>

app/views/hatestatements/showhate.html.erb
<center>
  <div class="smallrotbox" id="plane">
    <h1 class="bigtitle">Top <span class="lighthate">Hates</span></h1>
    <center class="rotateme" style="letter-spacing:1px;margin-top:-12px;font-size:60%;">Click ++ to promote</center>
  </div>
</center>
<div class="bubbleholder" style="height:400px;margin-top:-175px;">
  <% @hates.reverse.sort{|b,a| [Like.find_by_sql("SELECT DISTINCT LIKER FROM LIKES WHERE STATEMENTID = #{a.id}").size,a.created_at] <=> [Like.find_by_sql("SELECT DISTINCT LIKER FROM LIKES WHERE STATEMENTID = #{b.id}").size,b.created_at]}.each do |h| %>
<% next if !current_user and h.profanity%>  
<% next if params[:hater] and params[:hater] != h.submitter %>
  <div class="hatebubble" style="float:<%=["left","right"][rand(2)]%>">
    <div class="divrotate" style="text-align:center;"><a href="/hate/<%=h.id%>" style="font-weight:normal;color:black;text-decoration:none;">"<i>I hate <%=h.statement.downcase%></i>"</a> <div style="margin-top:10px;">~ <b><a style="color:#0a2360;text-decoration:none;" href="/hates/<%=h.submitter%>"><%=h.submitter.gsub("notloggedin","Anonymous")%></b></a>
      <a href="/agree/<%=h.id%>" style="text-decoration:none;"><span class="plus"><%=(Like.find_by_sql("SELECT DISTINCT LIKER FROM LIKES WHERE STATEMENTID = #{h.id}").size)%>++</span></a></div>
    <br><center class="lighthate" style="font-size:70%;"><a class ="lighthate" style="text-decoration:none;font-weight:normal;"href="/hate/<%=h.id%>"><%=Comment.find_all_by_statementid(h.id).size%> comments,</a> submitted <%=distance_of_time_in_words(Time.now,(Time.zone.parse(h.created_at.to_s)))%> ago.</center>
  </div>
  </div>
<% end %>
</div>

app/views/hatestatements/singlehate.html.erb
<div class="centerbox" id ="plane" style="height:auto;margin-top:-200px;">
  <div class="innerbox" style="text-align:center;height:auto;">
    <p class="rotatedtext"><b class="lighthate"><%=distance_of_time_in_words(Time.now,(Time.parse(@hate.created_at.to_s))).capitalize%> ago</b>, <br> <a style="color:#1a3370;text-decoration:none;" href="/hates/<%=@hate.submitter%>"><%=@hate.submitter.gsub("notloggedin","Anonymous")%></a> hated "<i class="lighthate"><%=@hate.statement%></i>".
    <br>
    This hate has <%=@themes.size%> common theme<%="s" if @themes.size != 1%>.
    <%=@themes if @themes.size > 0%>
  </div>
</div>
<div class="bubbleholder" style="height:260px;margin-top:0px;">
  <div class="commentform">
    <b class="lighthate">Create a new comment</b>
    <br>
    <%= form_for(:comment, :url => {:controller => "comments", :actiom => "create"}) do |f| %>
      <%=f.hidden_field(:statementid, :value => params[:id])%>
      <%=f.text_field(:commentbody, :class => "comment_input")%>
    <%end%>
  </div>
  <br>
  <div class="commentform" style="height:auto;">
    <center class="lighthate"><b>Existing Comments</b></center>
  <% @comments.each do |c| %>
    <div class="hatebubble" style="float:<%=["left","right"][rand(2)]%>;">
      <div class="divrotate" style="color:black;">
        "<i><%=c.commentbody%></i>" <a href="/hates/<%=c.submitter%>" style="text-decoration:none;"><b style="color:#0a2360;">~ <%=c.submitter%></b></a>
        <br> <br>
        <span class="lighthate">Submitted <%=distance_of_time_in_words(Time.now,(Time.zone.parse(c.created_at.to_s)))%> ago.</span>
    </div>
    </div>
  <% end %>
  <%= javascript_tag "
    document.getElementById('comment_commentbody').focus();
  "%>
  <div style="clear:both;"></div>
  <% if @comments.size == 0 %>
  <center class="lighthate" style="padding-top:20px;">This hate has no comments.</center>
  <%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Antisocial Network.</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding:0px;margin:0px;">
  <div class="topbar">
    <center>
      <%= link_to "Click here", "/hates"%> to find out what people hate! 
      | <% if current_user%>
        Logged in as <b><%=current_user.name%></b>.
        <%= link_to "Log out", log_out_path %>
      <% else %>
      Otherwise 
        <%= link_to "Sign up", sign_up_path %> or 
        <%= link_to "Log in", log_in_path %> 
      <% end %> | Tell us what you <%= link_to "hate", root_path%>.
    </center>
  </div>
  <%= yield %>
  <%= javascript_tag "
    function moveplane(x){
      var rottarget = -2;
      if (x >= rottarget){
        document.getElementById('plane').style.webkitTransform = 'rotate('+x+'deg)'
        var next = x-1;
        setTimeout('moveplane('+next+')',1);
      };
    };
    moveplane(12);
  "%>
  <div style="clear:both;">
  </div>
 <div class="bottombox">
   <center>
      <% @allhate = Hatestatement.find(:all)%>
      <% @lasts = Hatestatement.last([@allhate.size,10].min).reverse %>
      <% @lasts.each_with_index do |last,index| %>
        <div id=hate<%=index%> style="letter-spacing:1px;">
          <a style="text-decoration:none;font-weight:normal;" href="/hate/<%=last.id%>">"<i>I hate <%=last[:statement] if last[:statement].size < 70%><%="#{last[:statement][0..69]}..." if last[:statement].size >= 70%></i>" ~ <b><%=last[:submitter].gsub("notloggedin","Anonymous")%></b></a> <a style="text-decoration:none;" href="/agree/<%=last[:id]%>"><span style="margin-left:10px;margin-right:10px;" class="plus"><%=(Like.find_by_sql("SELECT DISTINCT LIKER FROM LIKES WHERE STATEMENTID = #{last[:id]}").size)%>++</span></a> <span class="lighthate"><%=distance_of_time_in_words(Time.now,(Time.zone.parse(last.created_at.to_s)))%> ago.</span> <span class="smallgreen">TIP: Click the ++ to agree.</class>
        </div>
      <% end %>
      <%= javascript_tag "
      function turnOffN(n){
        var i=0;
        for (i=0;i<n;i++){
          document.getElementById('hate'+i).style.display = 'none';
        };
      };
      function hateSwitch(x){
        turnOffN(#{[@allhate.size,10].min});
        document.getElementById('hate'+x).style.display = 'inline';
        var next = (x+1)%#{[@allhate.size,10].min};
        setTimeout(\"hateSwitch(\"+next+\")\",5000);
      };
      hateSwitch(0);"%>
    </center>
 </div>
</body>
</html>

app/views/likes/agree.html.erb
<h1>Likes#agree</h1>
<p>Find me in app/views/likes/agree.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
          <div class="error_messages">
            <center><h2 style="color:white;">Form is invalid. <%=@user.errors.full_messages.join(", ")%>.</h2></center>
          </div>
        <% end %>
<div class="centerbox">
  <center><h3 style="margin:15px;" class="bigtitle">Sign Up!</h3></cemter>
    <div class="rotatedcontent"style="border-radius:10px;background-color:#1a3370;margin:30px;border:solid 1px #0a2360;height:120px;">
      <%= form_for @user do |f| %>
        <div class="fieldcontainer">
          <p class="field">
            Username<br />
            <%= f.text_field(:name, :class => "textbox") %>
          </p>
          <p class="field">
            Email Address<br />
            <%= f.text_field(:email, :class => "textbox")  %>
          </p>
          <p class="field">
            Password<br />
            <%= f.password_field(:password, :class => "textbox")  %>
          </p>
          <p class="field">
            Password (again)<br />
            <%= f.password_field(:password_confirmation, :class => "textbox")  %>
          </p>
        <div style="clear:both;">
        </div>
        </div>
        <p class="button">
          <%=f.submit %>
        </p>
      <% end %>
    </div>
</div>